<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'goalio-forgot-password/email/forgot'           => __DIR__ . '/view/goalio-forgot-password/email/forgot.phtml',
    'goalio-forgot-password/forgot/forgot'          => __DIR__ . '/view/goalio-forgot-password/forgot/forgot.phtml',
    'goalio-forgot-password/forgot/passwordchanged' => __DIR__ . '/view/goalio-forgot-password/forgot/passwordchanged.phtml',
    'goalio-forgot-password/forgot/reset'           => __DIR__ . '/view/goalio-forgot-password/forgot/reset.phtml',
    'goalio-forgot-password/forgot/sent'            => __DIR__ . '/view/goalio-forgot-password/forgot/sent.phtml',
    'zfc-user/user/login'                           => __DIR__ . '/view/zfc-user/user/login.phtml',
);
